title: Chi Hang Suen # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Scientist | Machine Learning Specialist | Actuary
  <br><br>
  10+ years' experience in data analytics/data science/modelling. Worked in property & casualty insurance, digital startups.
  <br><br>
  <a href="https://www.linkedin.com/in/chihangs/">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
